In [1]:
import sympy as sym
import numpy as np
sym.init_printing()
from IPython.display import display,Math
from sympy.abc import x,y

In [2]:
A = [[1, 2],[3,4]]

A

In [3]:
A = [[1, 2],[3,4]]

type(A)

list

In [4]:
A = np.array([[1,2],[3,4]])
type(A)

numpy.ndarray

In [6]:
A = np.array([[1,2],[3,4]])
print(A)
display(Math(sym.latex(sym.simplify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [7]:
np.zeros([4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
mat = np.zeros([4,6])

mat[0,1] = 2
mat[2,4] = 7

mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)

mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

# Exercise 

f(x,y) = (4 + x)(2 - y)

x,y ∈ {0,1,2}

In [17]:
x,y = sym.symbols('x,y')
Fxy = (4+x)*(2-y)

xyset = range(0,3)

outmat = np.zeros([len(xyset),len(xyset)])

for i in xyset:
    for j in xyset:
        outmat[i,j] = Fxy.subs({x:i,y:j})

display(Math(sym.latex(sym.simplify(outmat))))

<IPython.core.display.Math object>